version: "3"

services:
  nexus:
    image: sonatype/nexus3:3.62.0
    container_name: nexus
    hostname: nexus
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./data:/nexus-data