version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.25.3
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    ports:
      - 80:80
