version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 123123123
    volumes:
      - ./data:/data
    command: server /data --console-address ":9090"
    restart: always